title: Ioana Draghici # your name (or website title) here
logo: "75284D59-056D-4814-ACCD-3874AEBF0FE3.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelors Degree in Environmental Science 
  <br><br>
  Univeristy of Maryland, Baltimore County
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
